### ISSUE TITLE
Not working for iPhone-X silmulator

### ISSUE THREAD

**Issue by taozhaolib** [CWBudde/cordova-plugin-wkwebview-inject-cookie#1]
I installed the plugin, and modified the file ".//platforms/ios/App.xcarchive/Products/Applications/ App.app/www/js/index.js" by adding the line: 

var app = {
    // Application Constructor
    initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },

    // deviceready Event Handler
    //
    // Bind any cordova events here. Common events are:
    // 'pause', 'resume', etc.
    onDeviceReady: function() {
        this.receivedEvent('deviceready');
    },

    // Update DOM on a Received Event
    receivedEvent: function(id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');
        // *** add the cookie handling line (IP is the computer running the backend server): ***//
        wkwebview.injectCookie('http://10.204.155.132:8888/');
        console.log('Received Event: ' + id);
    }
};

app.initialize();

The question is do I put the line into the correct file or the IP is not the way to be used for myDomain?

**Comment by taozhaolib** [comment]
Plus I am trying to set a http-only cookie.

**Comment by taozhaolib** [comment]
I just found I did not install the WKWebView plugin yet. Let me try it again.

**Comment by CWBudde** [comment]
The call to inject the cookie is nearly correct. There is one error, but that is my fault. It should read wkWebView and not wkwebview (as I also wrote in the example).

You can omit the protocol as it is not needed. All together the line could read as follows:

`wkWebView.injectCookie('10.204.155.132/');`

I'm not sure about the port, but I think you can leave it out here as well.

'http-only' cookies (and 'secure' cookies) work fine.

**Comment by taozhaolib** [comment]
Thank you. But my app might have something else going on. I heard that the cordova app by default uses UIWebView unless you install the WKWebView plugin? If so, I have not yet installed the WKWebView plugin, and my app is running UIWebView and still having the cookie issue. Is that true? Again, I'm running on the simulated iPhone X using xcode.

**Comment by CWBudde** [comment]
I don't use the simulator very often, so I can't tell about the behaviour there. However, this plugin requires WKWebView (instead of the default UIWebView). While the latter is currently still the default, it might switch next year when Apple will deprecate UIWebView.

However, by then the bug should have been fixed on a deeper level.

**Comment by taozhaolib** [comment]
Just tried and found it was not about the WKWebView issue. Thanks.
